# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [2]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [3]:
A = np.arange(10,50)[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [4]:
A = np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [5]:
A = np.array([1,2,0,0,4,0]).nonzero()
print(A)

(array([0, 1, 4], dtype=int32),)


#### 6. Create a 3x3 identity matrix 

In [6]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [7]:
A = np.random.rand(3,3,3)
print(A)

[[[0.63048245 0.24831004 0.5842706 ]
  [0.29863757 0.21504979 0.11908871]
  [0.24187442 0.72390606 0.81936277]]

 [[0.92514674 0.17634849 0.74954927]
  [0.2892259  0.30122211 0.95560723]
  [0.91294311 0.19775183 0.43939273]]

 [[0.97146841 0.56442569 0.87155703]
  [0.43871234 0.88218166 0.49039599]
  [0.58773219 0.19752212 0.77926176]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [8]:
A = np.random.rand(10,10)
print(A.max(), A.min())

0.9979368207397666 0.03601464976219659


#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [9]:
A = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [10]:
A = np.random.rand(5,3).dot(np.random.rand(3,2))
print(A)

[[0.71531595 0.89029561]
 [0.52990449 0.58151596]
 [0.80357975 1.02831894]
 [0.35369668 0.45372472]
 [0.69514502 1.18891221]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [11]:
A = np.tile(np.arange(5),(5,1))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [12]:
A = np.zeros((5,5)) + np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 13. Create a random vector of size 10 and sort it 

In [14]:
A = sorted(np.random.rand(10))
print(A)

[0.20238625125934717, 0.22201968085819246, 0.3960137556600819, 0.5528533302857908, 0.5993283006552019, 0.6069088089792384, 0.6117815093165505, 0.618169137060134, 0.6325144114857466, 0.9587865463308565]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [15]:
X = np.random.rand(5,10)
A = X - X.mean(axis=1).reshape(5,1)
print(A)

[[-0.21220795 -0.00585304  0.45929088  0.04224138  0.35632093 -0.36183139
  -0.05017246  0.3656143  -0.42334211 -0.17006054]
 [-0.15396757  0.09687447 -0.53125533 -0.36271659  0.14627058  0.24466863
   0.13586229  0.37610514 -0.09416147  0.14231984]
 [-0.09943031  0.16772853  0.29121482  0.33090195  0.16450035 -0.55275131
   0.0651805  -0.49914853  0.25543686 -0.12363287]
 [-0.17061578  0.15284694  0.17882163  0.0752952  -0.12032981 -0.29690878
  -0.05438135  0.13046957  0.32702459 -0.2222222 ]
 [ 0.04089788  0.17237614  0.02245087 -0.35057309  0.40807166  0.39566186
  -0.27146563  0.05304304 -0.12843043 -0.34203229]]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [16]:
A = np.arange(1,11)*np.arange(1,11).reshape(10,1)
print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [17]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
C = np.diag(A@B)
print(C)

[0.88163907 1.09308734 0.93021953 1.10648371 1.52320727]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [18]:
A = np.arange(1,6)

#1
B = np.insert(A,np.repeat(A[:4],3),0)
print(B)

#2
C = np.zeros(len(A) + 3*(len(A)-1))
C[::4] = A
print(C)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [19]:
A = np.arange(25).reshape(5,5)
B = A.copy()
A[[0,1]] = A[[1,0]]
print(A)
print('')
print(B)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [20]:
Z = np.random.randint(0,10,50)
A = np.bincount(Z).argmax()
print(A)

1


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [21]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10              
A = Z[np.argsort(Z)[-n:]]
print(A)

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [22]:
A = np.random.randint(1,4,(10,2))
B = np.unique(A, axis=0)
print(A)
print('')
print(B)

[[3 2]
 [2 2]
 [1 3]
 [3 2]
 [3 3]
 [3 3]
 [2 2]
 [3 2]
 [3 2]
 [2 3]]

[[1 3]
 [2 2]
 [2 3]
 [3 2]
 [3 3]]


#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [23]:
def moving_avg(arr,n):
  list = [arr[i:i+n].mean() for i in range(len(arr)-n+1)]
  return list

moving_avg(np.arange(10),3)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]

#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [24]:
A = np.random.rand(4,4)
index = np.nonzero(A>0.5)
B = [*zip(index[0],index[1])]
print(B)

[(0, 3), (1, 0), (1, 1), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2)]


#### 25. Write a function returning distance between two points

In [25]:
def distance(a,b):
  x1,y1 = a
  x2,y2 = b
  distance = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
  return distance

distance((1,1),(2,2))

1.4142135623730951